name = "vvidhya"
main = "./dist/worker.js" # Build output for the worker script (not needed for Pages)

[site]
bucket = "./static" # Static assets directory
include = ["**/*"] # Include all files
exclude = ["node_modules/**", "wrangler.toml", "package*.json"] # Exclude unnecessary files

[env.dev]
workers_dev = true
route = "/api/submit-contact-form"